export {
  evaluate,
  createRootEnvironment,
  type EvalResult,
  type EvalContext,
} from "./evaluator";

export {
  createEnvironment,
  extendEnvironment,
  lookupVariable,
  defineVariable,
  setVariable,
  type Environment,
} from "./environment";

export {
  valueToNode,
  nodeToValue,
  valuesEqual,
  isTruthy,
  isNumber,
  isString,
  isBoolean,
  isNil,
  isSymbol,
  isList,
  isFunction,
  isBuiltin,
  isCallable,
  isSequence,
  makeNumber,
  makeString,
  makeBoolean,
  makeNil,
  makeSymbol,
  makeList,
  makeFunction,
  makeBuiltin,
  makeExternalNamespace,
  type Value,
  type NumberValue,
  type StringValue,
  type BooleanValue,
  type NilValue,
  type SymbolValue,
  type ListValue,
  type FunctionClauseValue,
  type FunctionValue,
  type BuiltinValue,
  type BuiltinFunction,
} from "./values";
