export { analyzeProgram } from "./analyzer";
export type {
  AnalyzeOptions,
  AnalyzeResult,
  SemanticGraph,
  ModuleImportRecord,
  FlattenedImportBinding,
  ModuleExportRecord,
  ModuleResolver,
  ModuleResolutionRequest,
  ModuleResolutionResult,
  ModuleExportsLookup,
  ScopeRecord,
  SymbolRecord,
  SymbolKind,
  SemanticNodeRecord,
  NodeSymbolInfo,
  ScopeId,
  SymbolId,
  NodeId,
} from "./analyzer";
